# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 0
    gaps_out = 0
    border_size = 0
    layout = master
}

master {
    new_status = slave
    new_on_top = false
    new_on_active = none
    drop_at_cursor = false
    orientation = left
    always_keep_position = false
}

input {
    follow_mouse = 1
    mouse_refocus = false
}

cursor {
    hide_on_key_press = true
    warp_on_change_workspace = 1
    persistent_warps = false
}

binds {
    workspace_center_on = 1
}
